// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.35.0
// source: tunnel.proto

package tunnel

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	LightingService_GetLightingStatus_FullMethodName    = "/tunnel.LightingService/GetLightingStatus"
	LightingService_SetEmergencyLighting_FullMethodName = "/tunnel.LightingService/SetEmergencyLighting"
	LightingService_StreamLightingStatus_FullMethodName = "/tunnel.LightingService/StreamLightingStatus"
)

// LightingServiceClient is the client API for LightingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LightingServiceClient interface {
	GetLightingStatus(ctx context.Context, in *LightingStatusRequest, opts ...grpc.CallOption) (*LightingStatusResponse, error)
	SetEmergencyLighting(ctx context.Context, in *LightingControlRequest, opts ...grpc.CallOption) (*LightingControlResponse, error)
	StreamLightingStatus(ctx context.Context, opts ...grpc.CallOption) (LightingService_StreamLightingStatusClient, error)
}

type lightingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLightingServiceClient(cc grpc.ClientConnInterface) LightingServiceClient {
	return &lightingServiceClient{cc}
}

func (c *lightingServiceClient) GetLightingStatus(ctx context.Context, in *LightingStatusRequest, opts ...grpc.CallOption) (*LightingStatusResponse, error) {
	out := new(LightingStatusResponse)
	err := c.cc.Invoke(ctx, LightingService_GetLightingStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightingServiceClient) SetEmergencyLighting(ctx context.Context, in *LightingControlRequest, opts ...grpc.CallOption) (*LightingControlResponse, error) {
	out := new(LightingControlResponse)
	err := c.cc.Invoke(ctx, LightingService_SetEmergencyLighting_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightingServiceClient) StreamLightingStatus(ctx context.Context, opts ...grpc.CallOption) (LightingService_StreamLightingStatusClient, error) {
	stream, err := c.cc.NewStream(ctx, &LightingService_ServiceDesc.Streams[0], LightingService_StreamLightingStatus_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &lightingServiceStreamLightingStatusClient{stream}
	return x, nil
}

type LightingService_StreamLightingStatusClient interface {
	Send(*LightingStatusRequest) error
	Recv() (*LightingStatusResponse, error)
	grpc.ClientStream
}

type lightingServiceStreamLightingStatusClient struct {
	grpc.ClientStream
}

func (x *lightingServiceStreamLightingStatusClient) Send(m *LightingStatusRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *lightingServiceStreamLightingStatusClient) Recv() (*LightingStatusResponse, error) {
	m := new(LightingStatusResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// LightingServiceServer is the server API for LightingService service.
// All implementations must embed UnimplementedLightingServiceServer
// for forward compatibility
type LightingServiceServer interface {
	GetLightingStatus(context.Context, *LightingStatusRequest) (*LightingStatusResponse, error)
	SetEmergencyLighting(context.Context, *LightingControlRequest) (*LightingControlResponse, error)
	StreamLightingStatus(LightingService_StreamLightingStatusServer) error
	mustEmbedUnimplementedLightingServiceServer()
}

// UnimplementedLightingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLightingServiceServer struct {
}

func (UnimplementedLightingServiceServer) GetLightingStatus(context.Context, *LightingStatusRequest) (*LightingStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLightingStatus not implemented")
}
func (UnimplementedLightingServiceServer) SetEmergencyLighting(context.Context, *LightingControlRequest) (*LightingControlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetEmergencyLighting not implemented")
}
func (UnimplementedLightingServiceServer) StreamLightingStatus(LightingService_StreamLightingStatusServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamLightingStatus not implemented")
}
func (UnimplementedLightingServiceServer) mustEmbedUnimplementedLightingServiceServer() {}

// UnsafeLightingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LightingServiceServer will
// result in compilation errors.
type UnsafeLightingServiceServer interface {
	mustEmbedUnimplementedLightingServiceServer()
}

func RegisterLightingServiceServer(s grpc.ServiceRegistrar, srv LightingServiceServer) {
	s.RegisterService(&LightingService_ServiceDesc, srv)
}

func _LightingService_GetLightingStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LightingStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightingServiceServer).GetLightingStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LightingService_GetLightingStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightingServiceServer).GetLightingStatus(ctx, req.(*LightingStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LightingService_SetEmergencyLighting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LightingControlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightingServiceServer).SetEmergencyLighting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LightingService_SetEmergencyLighting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightingServiceServer).SetEmergencyLighting(ctx, req.(*LightingControlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LightingService_StreamLightingStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LightingServiceServer).StreamLightingStatus(&lightingServiceStreamLightingStatusServer{stream})
}

type LightingService_StreamLightingStatusServer interface {
	Send(*LightingStatusResponse) error
	Recv() (*LightingStatusRequest, error)
	grpc.ServerStream
}

type lightingServiceStreamLightingStatusServer struct {
	grpc.ServerStream
}

func (x *lightingServiceStreamLightingStatusServer) Send(m *LightingStatusResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *lightingServiceStreamLightingStatusServer) Recv() (*LightingStatusRequest, error) {
	m := new(LightingStatusRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// LightingService_ServiceDesc is the grpc.ServiceDesc for LightingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LightingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tunnel.LightingService",
	HandlerType: (*LightingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLightingStatus",
			Handler:    _LightingService_GetLightingStatus_Handler,
		},
		{
			MethodName: "SetEmergencyLighting",
			Handler:    _LightingService_SetEmergencyLighting_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamLightingStatus",
			Handler:       _LightingService_StreamLightingStatus_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "tunnel.proto",
}

const (
	EmergencyService_ReportEmergency_FullMethodName    = "/tunnel.EmergencyService/ReportEmergency"
	EmergencyService_GetEmergencyStatus_FullMethodName = "/tunnel.EmergencyService/GetEmergencyStatus"
	EmergencyService_ClearEmergency_FullMethodName     = "/tunnel.EmergencyService/ClearEmergency"
)

// EmergencyServiceClient is the client API for EmergencyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmergencyServiceClient interface {
	ReportEmergency(ctx context.Context, in *EmergencyAlert, opts ...grpc.CallOption) (*EmergencyStatusResponse, error)
	GetEmergencyStatus(ctx context.Context, in *EmergencyStatusRequest, opts ...grpc.CallOption) (*EmergencyStatusResponse, error)
	ClearEmergency(ctx context.Context, in *EmergencyStatusRequest, opts ...grpc.CallOption) (*EmergencyStatusResponse, error)
}

type emergencyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEmergencyServiceClient(cc grpc.ClientConnInterface) EmergencyServiceClient {
	return &emergencyServiceClient{cc}
}

func (c *emergencyServiceClient) ReportEmergency(ctx context.Context, in *EmergencyAlert, opts ...grpc.CallOption) (*EmergencyStatusResponse, error) {
	out := new(EmergencyStatusResponse)
	err := c.cc.Invoke(ctx, EmergencyService_ReportEmergency_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emergencyServiceClient) GetEmergencyStatus(ctx context.Context, in *EmergencyStatusRequest, opts ...grpc.CallOption) (*EmergencyStatusResponse, error) {
	out := new(EmergencyStatusResponse)
	err := c.cc.Invoke(ctx, EmergencyService_GetEmergencyStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emergencyServiceClient) ClearEmergency(ctx context.Context, in *EmergencyStatusRequest, opts ...grpc.CallOption) (*EmergencyStatusResponse, error) {
	out := new(EmergencyStatusResponse)
	err := c.cc.Invoke(ctx, EmergencyService_ClearEmergency_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmergencyServiceServer is the server API for EmergencyService service.
// All implementations must embed UnimplementedEmergencyServiceServer
// for forward compatibility
type EmergencyServiceServer interface {
	ReportEmergency(context.Context, *EmergencyAlert) (*EmergencyStatusResponse, error)
	GetEmergencyStatus(context.Context, *EmergencyStatusRequest) (*EmergencyStatusResponse, error)
	ClearEmergency(context.Context, *EmergencyStatusRequest) (*EmergencyStatusResponse, error)
	mustEmbedUnimplementedEmergencyServiceServer()
}

// UnimplementedEmergencyServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEmergencyServiceServer struct {
}

func (UnimplementedEmergencyServiceServer) ReportEmergency(context.Context, *EmergencyAlert) (*EmergencyStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportEmergency not implemented")
}
func (UnimplementedEmergencyServiceServer) GetEmergencyStatus(context.Context, *EmergencyStatusRequest) (*EmergencyStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEmergencyStatus not implemented")
}
func (UnimplementedEmergencyServiceServer) ClearEmergency(context.Context, *EmergencyStatusRequest) (*EmergencyStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearEmergency not implemented")
}
func (UnimplementedEmergencyServiceServer) mustEmbedUnimplementedEmergencyServiceServer() {}

// UnsafeEmergencyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmergencyServiceServer will
// result in compilation errors.
type UnsafeEmergencyServiceServer interface {
	mustEmbedUnimplementedEmergencyServiceServer()
}

func RegisterEmergencyServiceServer(s grpc.ServiceRegistrar, srv EmergencyServiceServer) {
	s.RegisterService(&EmergencyService_ServiceDesc, srv)
}

func _EmergencyService_ReportEmergency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmergencyAlert)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmergencyServiceServer).ReportEmergency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmergencyService_ReportEmergency_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmergencyServiceServer).ReportEmergency(ctx, req.(*EmergencyAlert))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmergencyService_GetEmergencyStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmergencyStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmergencyServiceServer).GetEmergencyStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmergencyService_GetEmergencyStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmergencyServiceServer).GetEmergencyStatus(ctx, req.(*EmergencyStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmergencyService_ClearEmergency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmergencyStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmergencyServiceServer).ClearEmergency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmergencyService_ClearEmergency_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmergencyServiceServer).ClearEmergency(ctx, req.(*EmergencyStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EmergencyService_ServiceDesc is the grpc.ServiceDesc for EmergencyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmergencyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tunnel.EmergencyService",
	HandlerType: (*EmergencyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportEmergency",
			Handler:    _EmergencyService_ReportEmergency_Handler,
		},
		{
			MethodName: "GetEmergencyStatus",
			Handler:    _EmergencyService_GetEmergencyStatus_Handler,
		},
		{
			MethodName: "ClearEmergency",
			Handler:    _EmergencyService_ClearEmergency_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tunnel.proto",
}
